version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  server.littlemarket:
    image: littlemarket/node
    stdin_open: true
    container_name: server.littlemarket
    build:
      context: ../server
      dockerfile: config/docker/Dockerfile
    environment:
      NODE_ENV: development
    labels:
      - traefik.frontend.rule=Host:server.littlemarketeng.com
      - traefik.docker.network=web
      - traefik.port=3011
    ports:
      - 3011:3011
    volumes:
      - ../server:/server.littlemarket
      - /server.littlemarket/node_modules
    networks:
      - internal
      - web
    restart: always
  postgresql.littlemarket:
    image: postgres
    container_name: postgresql.littlemarket
    environment:
      POSTGRES_DB: "main"
      POSTGRES_PASSWORD: "Postgres2019!"
    labels:
      - traefik.frontend.rule=Host:postgresql.littlemarketeng.com
      - traefik.docker.network=web
      - traefik.port=3012
    ports:
      - "3012:3012"
    networks:
      - internal
      - web
    volumes:
      - /var/lib/postgresql.littlemarket/data
    restart: always
